/**
 * Generates lib/content.ts by inlining all .md files as string exports.
 * This makes the app Workers-compatible — no fs.readFileSync at runtime.
 *
 * Run: node scripts/generate-content.mjs
 * Auto-runs before: npm run build (via prebuild hook)
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..', '..')
const OUT = path.join(__dirname, '..', 'lib', 'content.ts')

function readDir(dir) {
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(file => ({
      slug: file.replace(/\.md$/, ''),
      content: fs.readFileSync(path.join(dir, file), 'utf8')
        .replace(/\\/g, '\\\\')
        .replace(/`/g, '\\`')
        .replace(/\$\{/g, '\\${'),
    }))
}

const domains = readDir(path.join(ROOT, 'domains'))
const governance = readDir(path.join(ROOT, 'governance'))
const product = readDir(path.join(ROOT, 'product'))
const design = readDir(path.join(ROOT, 'design'))

const skillsContent = fs.readFileSync(path.join(ROOT, 'skills', 'opencode-skill.md'), 'utf8')
  .replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

const rfcContent = fs.readFileSync(path.join(ROOT, 'rfc-template.md'), 'utf8')
  .replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')

const lines = [
  '// AUTO-GENERATED by scripts/generate-content.mjs — do not edit manually',
  '// Run: node scripts/generate-content.mjs',
  '',
  'export const domainFiles: Record<string, string> = {',
  ...domains.map(d => `  ${JSON.stringify(d.slug)}: \`${d.content}\`,`),
  '}',
  '',
  'export const governanceFiles: Record<string, string> = {',
  ...governance.map(d => `  ${JSON.stringify(d.slug)}: \`${d.content}\`,`),
  '}',
  '',
  'export const productFiles: Record<string, string> = {',
  ...product.map(d => `  ${JSON.stringify(d.slug)}: \`${d.content}\`,`),
  '}',
  '',
  'export const designFiles: Record<string, string> = {',
  ...design.map(d => `  ${JSON.stringify(d.slug)}: \`${d.content}\`,`),
  '}',
  '',
  `export const skillsFile = \`${skillsContent}\``,
  '',
  `export const rfcFile = \`${rfcContent}\``,
]

fs.writeFileSync(OUT, lines.join('\n'))
console.log(`✓ Generated lib/content.ts (${domains.length} eng, ${governance.length} governance, ${product.length} product, ${design.length} design)`)
